global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node_exporter
    scrape_interval: 1s
    static_configs:
      - targets: ["192.168.0.104:9999"]
  - job_name: node_exporter1
    scrape_interval: 1s
    static_configs:
      - targets: ["192.168.0.104:9990"]